#!/bin/bash
echo " this is a maths program"
echo "Addition"
echo "Subtraction"
echo "Multiplication"
echo " Division"
echo "enter the first value  e.g.,a=x"
read a 
echo "enter the second value  e.g.,b=y"
read b 
sum=$($a+$b)
sub=$($a-$b)
mul=$($a*$b)
div=$($a/$b)
echo "the result of addition is $sum"
echo "the result of subtraction is $sub"
echo "the result of multiplication is $mul"
echo "the result of division is $div"
